# -*- coding: utf-8 -*-
"""Testes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXtI6njTp5DiP7Ht9qNqfUDdw98sy9uG
"""

import ipywidgets as widgets
from IPython.display import display
from datetime import datetime, date

def calcular_idade_completa(data_nascimento):
    try:
        # Garante que estamos lidando com datetime
        nascimento = datetime.combine(data_nascimento, datetime.min.time())
        agora = datetime.now()
        delta = agora - nascimento

        dias = delta.days
        segundos_restantes = delta.seconds

        anos = dias // 365
        meses = (dias % 365) // 30
        dias_restantes = (dias % 365) % 30

        horas = segundos_restantes // 3600
        minutos = (segundos_restantes % 3600) // 60
        segundos = segundos_restantes % 60

        return (
            f"Você tem {anos} anos, {meses} meses, {dias_restantes} dias, "
            f"{horas} horas, {minutos} minutos e {segundos} segundos."
        )
    except Exception as e:
        return f"Ocorreu um erro: {str(e)}"

output = widgets.Output()
date_picker = widgets.DatePicker(
    description='Data:',
    disabled=False
)
botao = widgets.Button(description="Calcular Idade")

def on_click(b):
    output.clear_output()
    if date_picker.value:
        resposta = calcular_idade_completa(date_picker.value)
        with output:
            print(f"Você: {date_picker.value.strftime('%d/%m/%Y')}")
            print(f"Bot: {resposta}\n")
    else:
        with output:
            print("Por favor, selecione uma data.")


botao.on_click(on_click)

display(date_picker, botao, output)