# -*- coding: utf-8 -*-
"""Testes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXtI6njTp5DiP7Ht9qNqfUDdw98sy9uG
"""

import streamlit as st
from datetime import datetime, date

st.title("🧓 Calculadora de Idade Completa")

def calcular_idade_completa(data_nascimento):
    try:
        nascimento = datetime.combine(data_nascimento, datetime.min.time())
        agora = datetime.now()
        delta = agora - nascimento

        dias = delta.days
        segundos_restantes = delta.seconds

        anos = dias // 365
        meses = (dias % 365) // 30
        dias_restantes = (dias % 365) % 30

        horas = segundos_restantes // 3600
        minutos = (segundos_restantes % 3600) // 60
        segundos = segundos_restantes % 60

        return (
            f"Você tem {anos} anos, {meses} meses, {dias_restantes} dias, "
            f"{horas} horas, {minutos} minutos e {segundos} segundos."
        )
    except Exception as e:
        return f"Ocorreu um erro: {str(e)}"

# Interface com Streamlit
data_nascimento = st.date_input("Selecione sua data de nascimento:")

if st.button("Calcular Idade"):
    if data_nascimento:
        st.markdown(f"**Você nasceu em:** {data_nascimento.strftime('%d/%m/%Y')}")
        resultado = calcular_idade_completa(data_nascimento)
        st.success(resultado)
    else:
        st.warning("Por favor, selecione uma data.")
